# - v1.0 - Configuration

options:
  # send staff noticies to all staff on all connected bungee servers
  use_bungeecord: true
  # uses the scoreboard feature to brand cheaters
  use_scoreboard_teams: true
  # permission used to test if the user can see staff notice
  staff_permission: 'hacx.staff'
  # permission used to test if the user can see public announcement
  announce_permission: 'hacx.announce'
  # reduce their violation counters every minute
  reduce_ticks: 1200

warning:
  announce: ''
  message: '&cYou are being recorded for possible cheating. &8(#{id})'
  staff: '&6[STAFF] &cThe player &3{player}&c is suspected of using &5&l{hack}&r. &8(#{id})'
  scoreboard_team: '&c[Suspicious]'

action:
  announce: '&f[&4WARN&f] &6Everyone watch out for the cheater &3{player}&6.'
  message: '&cYou have been branded as a cheater! &8(#{id})'
  staff: '&6[STAFF] &cThe player &3{player}&c is using &5&l{hack}&r. &8(#{id})'
  scoreboard_team: '&4[Cheater]'
  kick: true

ban:
  announce: '&f[&eNOTICE&f] &6The user &3{player}&6 has been banned for cheating.'
  message: '&cYou have been banned for cheating. &8(#{id})'
  staff: '&6[STAFF] &cThe player &3{player}&c has been &4banned&c for using &5&l{hack}&r. &8(#{id})'
  scoreboard_team: ''
  ban: true

rules:
  # General forms of attack
  Bad Packets:
    warning_level: 1
    action_level: 3
    ban_level: 15

  Impossible Interaction:
    warning_level: 1
    action_level: 3
    ban_level: 15

  Impossible Movements:
    warning_level: 1
    action_level: 3
    ban_level: 15

  #Combat related
  Criticals:
    warning_level: 3
    action_level: 5
    ban_level: 30

  Kill Aura:
    warning_level: 1
    action_level: 3
    ban_level: 7

  #Player Hacks
  Fast Eat:
    warning_level: 3
    action_level: 5
    ban_level: 10

  Fast Place:
    warning_level: 3
    action_level: 10
    ban_level: 25

  #Movement Hacks, while cheating have little benefit in combat
  Fly:
    warning_level: 10
    action_level: 30
    ban_level: 150

  Step:
    warning_level: 10
    action_level: 30
    ban_level: 150

  Speed:
    warning_level: 10
    action_level: 30
    ban_level: 150

  Glide:
    warning_level: 10
    action_level: 30
    ban_level: 150

  Jesus:
    warning_level: 10
    action_level: 30
    ban_level: 150

  No Fall:
    warning_level: 10
    action_level: 30
    ban_level: 150

  Headless:
    warning_level: 10
    action_level: 30
    ban_level: 150

  #Misc Stuff
  Spam:
    warning_level: -1
    action_level: -1
    ban_level: -1

messages:
  'no-access': '&4You do not have permission to this command.'
  'player-not-found': '&cPlayer not found.'
  'hac-console': '{player}({x},{y},{z},{ping}ping,{tps}tps) VIOLOATION: #{id} {type} {severity}'
