name: HACxtras
main: com.steamcraftmc.HACxtras.MainPlugin
version: '1.0'
author: rknapp
load: startup
commands:
  hacx:
    description: 'Commands to control the fate of a player.'
    usage: /<command> ban|brand|forgive|whitelist|reload <player>
    aliases: []
    permission: hacx.admin
    permission-message: 'ยง4You do not have permission to use this command.'
    default: op
